### ISSUE TITLE
Актуализировать информацию в src/configs/README.md

### ISSUE THREAD

**Issue by valentina-kustikova** [itlab-vision/openvino-dl-benchmark#154]

**Comment by KchnKchn** [comment]
@valentina-kustikova, актуализировал информацию, касающуюся заполнения конфигурации бенчмарка
@TheG1uy, нужно аутализировать информацию касательно заполнения конфигураций удаленного запуска и разворачивания нашей системы

**Comment by TheG1uy** [comment]
@valentina-kustikova @KchnKchn, в удаленном запуске актуальная информация

**Comment by valentina-kustikova** [comment]
@TheG1uy, там есть еще конфигурация для скриптов развертывания системы, которая совсем не описана в этом файле.

**Comment by TheG1uy** [comment]
@valentina-kustikova Уже добавил

**Comment by valentina-kustikova** [comment]
@TheG1uy, на будущее просьба все-таки работать в разных пулл-реквестах, а не в кучу все сваливать. Искать очень тяжело.
