### ISSUE TITLE
Реорганизовать директорию results

### ISSUE THREAD

**Issue by valentina-kustikova** [itlab-vision/openvino-dl-benchmark#158]
Надо сделать так, чтобы папка с результатами содержала html-таблицы с опубликованными на сайте результатами, чтобы мы не искали в почте последний нужный вариант. Поэтому предлагают реорганизовать директорию results и сделать следующую структуру:
`results`
|-->`validation` (текущее содержимое папки results)
|-->`benchmarking` (html-таблицы с указанием в именах даты публикации и версии OpenVINO)

**Comment by KchnKchn** [comment]
@valentina-kustikova, выполнено
