### ISSUE TITLE
Таблица с результатами классификации

### ISSUE THREAD

**Issue by valentina-kustikova** [itlab-vision/openvino-dl-benchmark#45]
@roma-roma97, надо доделать проверку корректности работы реализации синхронного режима для классификационных моделей.

**Comment by KchnKchn** [comment]
Результаты классификации готовы.

**Comment by valentina-kustikova** [comment]
@KchnKchn, а где соответствующий PR?

**Comment by KchnKchn** [comment]
Вы его уже закрыли. Все результаты для классификации и детектирования сделаны. Вопрос только для сегментации открыт.

**Comment by valentina-kustikova** [comment]
@valentina-kustikova, тогда эту задачу я закрою, а пулл-реквест буду смотреть целиком, когда будут результаты по сегментации.

**Comment by KchnKchn** [comment]
https://github.com/itlab-vision/openvino-dl-benchmark/pull/49 вот PR классификации.

**Comment by valentina-kustikova** [comment]
@valentina-kustikova, он уже в мастер-ветке.

**Comment by KchnKchn** [comment]
https://github.com/itlab-vision/openvino-dl-benchmark/pull/65 результаты детекшена

**Comment by valentina-kustikova** [comment]
@KchnKchn, этот тоже уже в мастер-ветке.

**Comment by KchnKchn** [comment]
Ну так да. Поэтому эти задачи выполнены.
