### ISSUE TITLE
Конфигурационные файлы к разным компонентам

### ISSUE THREAD

**Issue by valentina-kustikova** [itlab-vision/openvino-dl-benchmark#48]
@KchnKchn, необходимо вынести все шаблоны конфигурационных файлов (лежащие в `src/benchmark`, `src/converter` и других местах) в отдельную директорию `configs` в папке `src`. Для каждого конфигурационного файла надо хранить шаблон, содержащий только теги, и пример заполнения. Конфигурации, содержащие специфичную для нас информацию (пути, машины, параметры доступа и прочее), надо хранить у себя локально и в закрытом виде, доступном только участникам проекта.

**Comment by KchnKchn** [comment]
@valentina-kustikova, не понял каким образом реализовать хранение в закрытом виде, доступным только участникам проекта.

**Comment by valentina-kustikova** [comment]
Могу предложить 2 варианта:
1. Папка на google drive, доступная только участникам.
2. Закрытый репозиторий.

**Comment by KchnKchn** [comment]
@valentina-kustikova, я залью файлы конфигурации на google drive.

**Comment by KchnKchn** [comment]
@valentina-kustikova, я залил файлы на диск нашего проекта. Отправил pull request в репозиторий с изменениями.
