### ISSUE TITLE
Конфигурационные файлы удаленного запуска бэнчмарка

### ISSUE THREAD

**Issue by valentina-kustikova** [itlab-vision/openvino-dl-benchmark#52]
@TheG1uy, переместите, пожалуйста, конфигурационные файлы удаленного запуска бэнчмарка `remote_config_template.xml` и пример его заполнения `remote_config.xml` в директорию `configs`. Файл с актуальной информацией о машинах и данных авторизации надо поместить на Google Drive в директорию, куда Александр переместил другие конфигурации, не надо их хранить в открытом репозитории.

**Comment by TheG1uy** [comment]
Сделано.
