### ISSUE TITLE
Объединение функций обработки выхода модели

### ISSUE THREAD

**Issue by valentina-kustikova** [itlab-vision/openvino-dl-benchmark#60]
@roma-roma97, @TheG1uy (@FenixFly, @KchnKchn), в скриптах `inference_sync_mode.py` и `inference_async_mode.py` есть функции обработки выхода нейросетевых моделей в зависимости от задачи. Можно ли эти функции вынести в отдельный модуль (очень похоже, что код идентичен и не зависит от режима запуска)? Если можно, то надо это сделать, поскольку сейчас у нас похоже присутствует дублирование кода.

**Comment by KchnKchn** [comment]
Да. Код идентичен. Сегодня исправлю.

**Comment by KchnKchn** [comment]
Вынес все инварианты в модули. Жду ревью кода.
Задача выполнена!
